version: "3.9"

services:

  db:
    restart: always
    image: postgres
    container_name: postgres_mines
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - "$POSTGRES_PORT:5432"


volumes:
  postgres_data: