version: "3.9"

services:

  db:
    image: postgres
    restart: always
    container_name: postgres_mines
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - "$POSTGRES_PORT:5432"

  cache:
    image: redis
    restart: always
    container_name: redis_mines
    ports:
      - "$REDIS_PORT:6379"

volumes:
  postgres_data:
