# Generated by Django 4.0.4 on 2022-05-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quantity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
