# Generated by Django 4.0.4 on 2022-06-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='quantity',
            new_name='balance',
        ),
    ]
