# Generated by Django 4.0.4 on 2022-06-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomb',
            old_name='hash',
            new_name='hash_bomb_in',
        ),
    ]
