# Generated by Django 4.0.4 on 2022-05-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomb',
            name='subsequence',
            field=models.TextField(blank=True),
        ),
    ]
