# Generated by Django 4.0.4 on 2022-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0002_rename_hash_bomb_hash_bomb_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomb',
            name='hash_bomb_in',
            field=models.JSONField(),
        ),
    ]
