# Generated by Django 4.0.4 on 2022-05-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0002_bomb_subsequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomb',
            name='is_open',
        ),
    ]
