# Generated by Django 4.0.4 on 2022-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0003_remove_bomb_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomb',
            old_name='subsequence',
            new_name='bomb_in',
        ),
        migrations.AddField(
            model_name='bomb',
            name='open_at',
            field=models.TextField(blank=True),
        ),
    ]
