# Generated by Django 4.0.4 on 2022-05-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0004_rename_subsequence_bomb_bomb_in_bomb_open_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomb',
            name='sum_right_now',
        ),
        migrations.AddField(
            model_name='bomb',
            name='price_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bomb',
            name='open_at',
            field=models.TextField(default='[]'),
        ),
    ]
