# Generated by Django 4.0.4 on 2022-05-31 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0005_remove_bomb_sum_right_now_bomb_price_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomb',
            name='open_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
