# Generated by Django 4.0.4 on 2022-05-31 09:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0006_alter_bomb_open_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomb',
            name='bomb_in',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
