# Generated by Django 4.0.4 on 2022-05-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0009_alter_bomb_open_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomb',
            old_name='open_at',
            new_name='opened',
        ),
    ]
