# Generated by Django 4.0.4 on 2022-05-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomb_game', '0010_rename_open_at_bomb_opened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomb',
            options={'verbose_name': 'Игра бомбочки'},
        ),
        migrations.AlterModelTable(
            name='bomb',
            table='bomb',
        ),
    ]
